### ISSUE TITLE
Make Solid OS compatible with ESS

### ISSUE THREAD

**Issue by michielbdejong** [solid/solidos#33]
In order to make Solid OS compatible with https://pod-compat.inrupt.com/ we need (afaik) 5 things:

* [ ] [Use webid-oidc-dpop instead of webid-oidc-legacy](https://github.com/solid/mashlib/pull/104)
* [ ] [Use Etags instead of sparql-update semaphore](https://github.com/linkeddata/rdflib.js/issues/482)
* [ ] Wait for https://github.com/solid/specification/issues/246#issuecomment-795084362 to be resolved
* [ ] Deal with [non-public acl links](https://github.com/solid/specification/pull/248#issuecomment-795118407)
* [ ] Wait for https://github.com/solid/specification/issues/193#issuecomment-795088636 to be resolved

**Comment by michielbdejong** [comment]
Also, Inrupt are dropping WAC support now.
